### ISSUE TITLE
confused with the label list

### ISSUE THREAD

**Issue by passion3394** [ApolloScapeAuto/dataset-api#10]
labels = [
    #           name     id trainId      category  catId hasInstances ignoreInEval            color
    Label(     'void' ,   0 ,     0,        'void' ,   0 ,      False ,      False , (  0,   0,   0) ),
    Label(    's_w_d' , 200 ,     1 ,   'dividing' ,   1 ,      False ,      False , ( 70, 130, 180) ),
    Label(    's_y_d' , 204 ,     2 ,   'dividing' ,   1 ,      False ,      False , (220,  20,  60) ),
    Label(  'ds_w_dn' , 213 ,     3 ,   'dividing' ,   1 ,      False ,       True , (128,   0, 128) ),
    Label(  'ds_y_dn' , 209 ,     4 ,   'dividing' ,   1 ,      False ,      False , (255, 0,   0) ),
    Label(  'sb_w_do' , 206 ,     5 ,   'dividing' ,   1 ,      False ,       True , (  0,   0,  60) ),
    Label(  'sb_y_do' , 207 ,     6 ,   'dividing' ,   1 ,      False ,       True , (  0,  60, 100) ),
    Label(    'b_w_g' , 201 ,     7 ,    'guiding' ,   2 ,      False ,      False , (  0,   0, 142) ),
    Label(    'b_y_g' , 203 ,     8 ,    'guiding' ,   2 ,      False ,      False , (119,  11,  32) ),
    Label(   'db_w_g' , 211 ,     9 ,    'guiding' ,   2 ,      False ,       True , (244,  35, 232) ),
    Label(   'db_y_g' , 208 ,    10 ,    'guiding' ,   2 ,      False ,       True , (  0,   0, 160) ),
    Label(   'db_w_s' , 216 ,    11 ,   'stopping' ,   3 ,      False ,       True , (153, 153, 153) ),
    Label(    's_w_s' , 217 ,    12 ,   'stopping' ,   3 ,      False ,      False , (220, 220,   0) ),
    Label(   'ds_w_s' , 215 ,    13 ,   'stopping' ,   3 ,      False ,       True , (250, 170,  30) ),
    Label(    's_w_c' , 218 ,    14 ,    'chevron' ,   4 ,      False ,       True , (102, 102, 156) ),
    Label(    's_y_c' , 219 ,    15 ,    'chevron' ,   4 ,      False ,       True , (128,   0,   0) ),
    Label(    's_w_p' , 210 ,    16 ,    'parking' ,   5 ,      False ,      False , (128,  64, 128) ),
    Label(    's_n_p' , 232 ,    17 ,    'parking' ,   5 ,      False ,       True , (238, 232, 170) ),
    Label(   'c_wy_z' , 214 ,    18 ,      'zebra' ,   6 ,      False ,      False , (190, 153, 153) ),
    Label(    'a_w_u' , 202 ,    19 ,  'thru/turn' ,   7 ,      False ,       True , (  0,   0, 230) ),
    Label(    'a_w_t' , 220 ,    20 ,  'thru/turn' ,   7 ,      False ,      False , (128, 128,   0) ),
    Label(   'a_w_tl' , 221 ,    21 ,  'thru/turn' ,   7 ,      False ,      False , (128,  78, 160) ),
    Label(   'a_w_tr' , 222 ,    22 ,  'thru/turn' ,   7 ,      False ,      False , (150, 100, 100) ),
    Label(  'a_w_tlr' , 231 ,    23 ,  'thru/turn' ,   7 ,      False ,       True , (255, 165,   0) ),
    Label(    'a_w_l' , 224 ,    24 ,  'thru/turn' ,   7 ,      False ,      False , (180, 165, 180) ),
    Label(    'a_w_r' , 225 ,    25 ,  'thru/turn' ,   7 ,      False ,      False , (107, 142,  35) ),
    Label(   'a_w_lr' , 226 ,    26 ,  'thru/turn' ,   7 ,      False ,      False , (201, 255, 229) ),
    Label(   'a_n_lu' , 230 ,    27 ,  'thru/turn' ,   7 ,      False ,       True , (0,   191, 255) ),
    Label(   'a_w_tu' , 228 ,    28 ,  'thru/turn' ,   7 ,      False ,       True , ( 51, 255,  51) ),
    Label(    'a_w_m' , 229 ,    29 ,  'thru/turn' ,   7 ,      False ,       True , (250, 128, 114) ),
    Label(    'a_y_t' , 233 ,    30 ,  'thru/turn' ,   7 ,      False ,       True , (127, 255,   0) ),
    Label(   'b_n_sr' , 205 ,    31 ,  'reduction' ,   8 ,      False ,      False , (255, 128,   0) ),
    Label(  'd_wy_za' , 212 ,    32 ,  'attention' ,   9 ,      False ,       True , (  0, 255, 255) ),
    Label(  'r_wy_np' , 227 ,    33 , 'no parking' ,  10 ,      False ,      False , (178, 132, 190) ),
    Label( 'vom_wy_n' , 223 ,    34 ,     'others' ,  11 ,      False ,       True , (128, 128,  64) ),
    Label(   'om_n_n' , 250 ,    35 ,     'others' ,  11 ,      False ,      False , (102,   0, 204) ),
    Label(    'noise' , 249 ,   255 ,    'ignored' , 255 ,      False ,       True , (  0, 153, 153) ),
    Label(  'ignored' , 255 ,   255 ,    'ignored' , 255 ,      False ,       True , (255, 255, 255) ),
]

Firstly, thanks for your dataset, I have a question:
unlike the label list of cityscape, the label list of Apollo lane dataset is different. In my opinion, the trainId of 'void' should be 255(ignored), because it shouldn't be evaluated. Is that right?

**Comment by pengwangucla** [comment]
That is correct

**Comment by passion3394** [comment]
@pengwangucla I understand it now, thanks.

**Comment by passion3394** [comment]
@pengwangucla could you share the trainId of the lane marking? just like cityscape. Users can convert the label pixels to trainId with your label definition, but it's time-consuming.

**Comment by dingfuzhou** [comment]
> @pengwangucla could you share the trainId of the lane marking? just like cityscape. Users can convert the label pixels to trainId with your label definition, but it's time-consuming.

Thanks for your question. Actually, the trainId is already included in our scripts. For detailed information, please refer to this file:  /lane_segmentation/helpers/laneMarkDetection.py

**Comment by passion3394** [comment]
@dingfuzhou I think my point is that it's better for Baidu to share the label image of trainIds,not the label color.

**Comment by passion3394** [comment]
@dingfuzhou @pengwangucla I have another question, what's the baseline between the camera 5 and camera 6 of the Apollo scene dataset ? Could you give me the info, thanks very much!

**Comment by jianghe01** [comment]
@passion3394 i think you can get it from the pose.txt which is the extrinsic matrix of camera 5 and camera 6.

**Comment by passion3394** [comment]
@jianghe01 thanks for your reply. 
where can I get the pose.txt?

**Comment by jianghe01** [comment]
It should be included in the self-localization dataset I think.

发件人: passion3394 <notifications@github.com>
发送时间: 2018年11月1日 14:54
收件人: ApolloScapeAuto/dataset-api <dataset-api@noreply.github.com>
抄送: Jiang,He <jianghe01@baidu.com>; Mention <mention@noreply.github.com>
主题: Re: [ApolloScapeAuto/dataset-api] confused with the label list (#10)


@jianghe01<https://github.com/jianghe01> thanks for your reply.
where can I get the pose.txt?

**Comment by passion3394** [comment]
@jianghe01 maybe. because I can't find the pose.txt in the apollo scene dataset. Could you please send me the pose.txt if you have at hand?

**Comment by passion3394** [comment]
@jianghe01 thank you very much. I got the answer.

**Comment by CaptainEven** [comment]
@passion3394 May i ask about the metric baseline value？
