### ISSUE TITLE
Is the website permanently offline?

### ISSUE THREAD

**Issue by lannio** [ApolloScapeAuto/dataset-api#100]
**http://apolloscape.auto/submit.html**
Hello, I've been following the Apollo dataset recently, but I found that the website can't be opened. Is it permanently offline? thank you

**Comment by sibozhang** [comment]
sorry for the inconvenience, it will be back soon.

**Comment by sibozhang** [comment]
website is online now

**Comment by lannio** [comment]
Thanks so much！
