### ISSUE TITLE
I cannot find 'car_models' in 'car_instance' dataset

### ISSUE THREAD

**Issue by alexbuyval** [ApolloScapeAuto/dataset-api#11]
Hi

First of all, thank you for excellent dataset!

In your readme there is a mention that 'car_instance' dataset contains 'car_model' directory with car meshes. I have download '3d-car-understanding-train.tar.gz' from [here](https://apolloscape.auto/car_instance.html), however there are no such directory :(
![image](https://user-images.githubusercontent.com/2115811/47769621-8914c600-dced-11e8-9ffa-3d02670032e1.png)

Where may I find the car models?

Thank you!

**Comment by DapengFeng** [comment]
@ApolloScapeAuto I meet the same problem, where may I find the car models?
Thank you!

**Comment by dingfuzhou** [comment]
> @ApolloScapeAuto I meet the same problem, where may I find the car models?
> Thank you!

Thanks for your attention. We will update our models soon!

**Comment by dingfuzhou** [comment]
> > > @ApolloScapeAuto I meet the same problem, where may I find the car models?
> > > Thank you!
> > 
> > 
> > Thanks for your attention. We will update our models soon!
> 
> I am so pleased to hear from you! Another question. Should I re-download the whole 'car_instance' dataset after you update the car models?

Hi DapengFeng,
We have updated our data. You can find the 3D car model in the 3d_car_instance_sample.tar.gz via the following website http://apolloscape.auto/car_instance.html. Please let us know if you have further questions.

Cheers

Dingfu

**Comment by dingfuzhou** [comment]
> Hi
> 
> First of all, thank you for excellent dataset!
> 
> In your readme there is a mention that 'car_instance' dataset contains 'car_model' directory with car meshes. I have download '3d-car-understanding-train.tar.gz' from [here](https://apolloscape.auto/car_instance.html), however there are no such directory :(
> ![image](https://user-images.githubusercontent.com/2115811/47769621-8914c600-dced-11e8-9ffa-3d02670032e1.png)
> 
> Where may I find the car models?
> 
> Thank you!
Hi alexbuyval,
Sorry for late reply. We have updated our data. You can find the 3D car model in the 3d_car_instance_sample.tar.gz via the following website http://apolloscape.auto/car_instance.html. Please let us know if you have further questions.

Cheers

Dingfu

**Comment by alexbuyval** [comment]
@dingfuzhou 

Thank you!
