### ISSUE TITLE
Unable to login to apolloscape.auto 

### ISSUE THREAD

**Issue by MohammedCHGHAF** [ApolloScapeAuto/dataset-api#114]
Hello, 

I have been trying to use either github or google to loign to apolloscape.auto/ using this page: http://apolloscape.auto/login.html.

I have tried Firefox and Google Chrome to get access to the download page. However, all download links keep leading to this page: http://apolloscape.auto/login.html 

Is there a way to download the dataset please ? 

Thank you very much in advance!

**Comment by sibozhang** [comment]
Website is working now

**Comment by sibozhang** [comment]
You can download dataset through link directly, such as wget https://ad-apolloscape.cdn.bcebos.com/trajectory/prediction_train.zip
