### ISSUE TITLE
Unable to login Apolloscape

### ISSUE THREAD

**Issue by salt0107fish** [ApolloScapeAuto/dataset-api#123]
Hi, 
I have been trying to login to your website http://apolloscape.auto/login.html but always fail. Is there something wrong? Thank you.

**Comment by CuberrChen** [comment]
I encountered the same problem. It is estimated that there is a problem with the server？

**Comment by sibozhang** [comment]
Hi, apolloscape user: Login and submit function has been deactivated. If you need download full dataset, please send email to apollscapeauto@gmail.com. Thank you!

**Comment by salt0107fish** [comment]
> Hi, apolloscape user: Login and submit function has been deactivated. If you need download full dataset, please send email to [apollscapeauto@gmail.com](mailto:apollscapeauto@gmail.com). Thank you!

Thank you for your reply~
