### ISSUE TITLE
Can't log in to the official website account 

### ISSUE THREAD

**Issue by ivsn-xdw** [ApolloScapeAuto/dataset-api#135]
Can't log in to the official website account

**Comment by Wangbiao2** [comment]
I encountered the same problem, have you solved it?  Thank you！！

**Comment by sibozhang** [comment]
Website is no longer able to login and submit result.

**Comment by zehranrgi** [comment]
> Website is no longer able to login and submit result.

It would help if you archived this repo. without evaluation, the dataset doesn't make sense. thank you.
