### ISSUE TITLE
About the trajectory prediction section of the API

### ISSUE THREAD

**Issue by 76qian** [ApolloScapeAuto/dataset-api#138]
Hello, I am currently testing code using the trajectory prediction section of the API, and I have two questions to ask you.
1. I encountered an error while running the test code - AttributeError: 'map' object has no attribute 'count'. The error is shown in the figure. How can I resolve this error?
2. After commenting out the 41st line of code, the code can run successfully. I input the results obtained from other models into this code, and the final test results differ greatly from the evaluation results. The evaluation results are WSADE=0.827 and WSFDE=1.479, but the test results are as shown in the second figure. What may be the reason for this?
I have been troubled by these issues for a long time and look forward to your reply and help. I will express my gratitude to you when publishing my paper.
<img width="331" alt="微信图片_20230510101526" src="https://github.com/ApolloScapeAuto/dataset-api/assets/96508781/5a90658f-052a-40cf-82bd-cac9d4aa876a">
<img width="318" alt="微信图片_20230510101542" src="https://github.com/ApolloScapeAuto/dataset-api/assets/96508781/0245d03a-cae1-41dd-ab2a-ca16f5b76729">

**Comment by sibozhang** [comment]
#139
