### ISSUE TITLE
dataset-api-master\trajectory_prediction\readme.md中 Data Structure有部分信息不理解

### ISSUE THREAD

**Issue by xuexisuanfa** [ApolloScapeAuto/dataset-api#142]
dataset-api-master\trajectory_prediction\readme.md中 Data Structure有部分信息不理解。
Data Structure中的信息如下：
## Data Structure
The folder structure of the trajectory prediction is as follows:

1. prediction_train.zip: training data for trajectory prediction.
   * Each file is a 1min sequence with 2fps.
   * Each line in a file contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.
   * There are five different object types as shown in following table. During the evaluation in this challenge, we treat the first two types, small vehicle and big vehicle, as one type (vehicle).
   
| object_type 	| small vehicles 	| big vehicles 	| pedestrian 	| motorcyclist and bicyclist 	| others 	|
|-------------	|----------------	|--------------	|------------	|----------------------------	|--------	|
| ID          	| 1              	| 2            	| 3          	| 4                          	| 5      	|

   * Position is given in the world coordinate system. The unit for the position and bounding box is meter.
   * The heading value is the steering radian with respect to the direction of the object.
   * In this challenge, we mainly evaluate predicted position_x and position_y in the next 3 seconds.
   
2. prediction_test.zip: testing data for trajectory prediction.
   * Each line contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.

   * A testing sequence contains every six frames in the prediction_test.txt. Each sequence is evaluated independently.

针对“  * Each line contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.”中的heading是什么意思？，还有position_x, position_y, position_z是什么坐标系的坐标，该坐标系的原点在哪，x轴方向 y方向 z轴方向又是指向哪？？？？？

**Comment by DingLei627** [comment]
I have the similar doubts about Data Structure,  for example: in the "tracking_train_pcd_1" folder , it have many subfolder,such as "result_9048_1_frame","result_9048_3_frame"....and so on,  and in "result_9048_3_frame", it have many sub_files, such as "233.pcd","238.pcd"....and so on, so what means of "233.pcd" is a obj id? but I visualize it it look like a full frame lidar data, as show in the following figure:
![ReadApolloScape_01_6qw7ja8L0B](https://github.com/ApolloScapeAuto/dataset-api/assets/49090387/b35e8649-af1b-48db-b815-4254ef84b8aa)

**Comment by sibozhang** [comment]
> dataset-api-master\trajectory_prediction\readme.md中 Data Structure有部分信息不理解。 Data Structure中的信息如下：
> 
> ## Data Structure
> The folder structure of the trajectory prediction is as follows:
> 
> 1. prediction_train.zip: training data for trajectory prediction.
>    
>    * Each file is a 1min sequence with 2fps.
>    * Each line in a file contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.
>    * There are five different object types as shown in following table. During the evaluation in this challenge, we treat the first two types, small vehicle and big vehicle, as one type (vehicle).
> 
> object_type	small vehicles	big vehicles	pedestrian	motorcyclist and bicyclist	others
> ID	1	2	3	4	5
> * Position is given in the world coordinate system. The unit for the position and bounding box is meter.
> * The heading value is the steering radian with respect to the direction of the object.
> * In this challenge, we mainly evaluate predicted position_x and position_y in the next 3 seconds.
> 
> 2. prediction_test.zip: testing data for trajectory prediction.
>    
>    * Each line contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.
>    * A testing sequence contains every six frames in the prediction_test.txt. Each sequence is evaluated independently.
> 
> 针对“ * Each line contains frame_id, object_id, object_type, position_x, position_y, position_z, object_length, object_width, object_height, heading.”中的heading是什么意思？，还有position_x, position_y, position_z是什么坐标系的坐标，该坐标系的原点在哪，x轴方向 y方向 z轴方向又是指向哪？？？？？

heading 是 车头朝向， 坐标系的原点在脱敏的gps位置。heading is the heading of the vehicle, and the origin of the coordinate system is at the desensitized GPS position.

**Comment by sibozhang** [comment]
> I have the similar doubts about Data Structure, for example: in the "tracking_train_pcd_1" folder , it have many subfolder,such as "result_9048_1_frame","result_9048_3_frame"....and so on, and in "result_9048_3_frame", it have many sub_files, such as "233.pcd","238.pcd"....and so on, so what means of "233.pcd" ? It is a object id? but I visualized it, it look like a full frame lidar data, not a single object, as show in the following figure: ![ReadApolloScape_01_6qw7ja8L0B](https://private-user-images.githubusercontent.com/49090387/283651861-b35e8649-af1b-48db-b815-4254ef84b8aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODUwMTAsIm5iZiI6MTcwNDc4NDcxMCwicGF0aCI6Ii80OTA5MDM4Ny8yODM2NTE4NjEtYjM1ZTg2NDktYWYxYi00OGRiLWI4MTUtNDI1NGVmODRiOGFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDA3MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkZjQ5ZmFlN2Y1MWUwYmUzYWFmMWY2NTUzOWI3ZjI4YzlmNzcxYTI0YmY2MzdiMmViMjY4MzQ1NjQwM2MxMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v8RN9J-3XLn_gkPiy6YZmeUppVYL-VUgDuFZgJWA-x0)

233.pcd or xxx.pcd is the frame id
