### ISSUE TITLE
Keypoint annotations

### ISSUE THREAD

**Issue by krrish94** [ApolloScapeAuto/dataset-api#15]
I cannot seem to find keypoint annotations for cars in the dataset. In the paper, you seem to have a 66 keypoint model per car. Is there something I'm missing here, or have the keypoints not been released?

**Comment by pengwangucla** [comment]
Sure, we plan to release the full content in the paper too.  Need some time to clean up the keypoints to right json format to facilitate eval, etc.

**Comment by Qiaojun-Feng** [comment]
The dataset on http://apolloscape.auto/car_instance.html hasn’t been updated to include 3D keypoints annotations(by 02/01), right?

**Comment by krrish94** [comment]
Yeah, it does now :)
