### ISSUE TITLE
Vehicles are not rendered correctly

### ISSUE THREAD

**Issue by ThoBaro** [ApolloScapeAuto/dataset-api#16]
When using the provided scripts the pose information seems incorrect. In both sample_data and training some cars are flipped (see screenshots).

Any ideas?
![rendering_example_data](https://user-images.githubusercontent.com/30796832/49800859-e36f6080-fd48-11e8-8d69-87acb8c308a5.png)
![rendering_171206_034636094_camera_5](https://user-images.githubusercontent.com/30796832/49800863-e4a08d80-fd48-11e8-8d0c-0b7ab8198554.png)

**Comment by Tbarowski** [comment]
@pengwangucla @ApolloScapeAuto Can you make a statement regarding this?

**Comment by Tbarowski** [comment]
In https://github.com/ApolloScapeAuto/dataset-api/issues/1#issuecomment-455473902 was identified that it seems like different model versions are existing. Until this issue is fixed use the models from https://www.jianguoyun.com/p/DfzeH4YQ9cyhBhiKgJkB.

**Comment by pengwangucla** [comment]
I have left Baidu long times ago. Sorry for not capturing these issues. Thanks for all the efforts in helping us identify all the issues. Good to see it is fixed
