### ISSUE TITLE
Trajectory dataset

### ISSUE THREAD

**Issue by kwea123** [ApolloScapeAuto/dataset-api#18]
Hi, 
Thanks for your great work. When do you intend to release the trajectory dataset as described [here](http://apolloscape.auto/trajectory.html)?
Thanks in advance.

**Comment by sibozhang** [comment]
the sample data is on http://apolloscape.auto/trajectory.html now, full data coming soon

**Comment by kwea123** [comment]
Thanks. But why is the sequence not continuous? For example in `sample_image_1`, the interval between image 77 and 78 is longer than other frames. According to the label, it is 200ms instead of 100ms. Is this intentional?

**Comment by sanggehouzhihoujue** [comment]
@sibozhang Hello， where is the evaluation.py for evaluating the trajectory test result？ I‘m always failed to submit the result.txt, so I need the evaluation.py to test my text format.

**Comment by ApolloScapeAuto** [comment]
> @sibozhang Hello， where is the evaluation.py for evaluating the trajectory test result？ I‘m always failed to submit the result.txt, so I need the evaluation.py to test my text format.

https://github.com/ApolloScapeAuto/dataset-api/blob/master/trajectory_prediction/evaluation.py

**Comment by sibozhang** [comment]
> @sibozhang Hello， where is the evaluation.py for evaluating the trajectory test result？ I‘m always failed to submit the result.txt, so I need the evaluation.py to test my text format.

https://github.com/ApolloScapeAuto/dataset-api/tree/master/trajectory_prediction

**Comment by sibozhang** [comment]
> Thanks. But why is the sequence not continuous? For example in `sample_image_1`, the interval between image 77 and 78 is longer than other frames. According to the label, it is 200ms instead of 100ms. Is this intentional?

Please use Training data and Testing data for research. Camera image is just examples for visualization.
