### ISSUE TITLE
error when loading pkl file of cars

### ISSUE THREAD

**Issue by Pony-Kelei** [ApolloScapeAuto/dataset-api#21]
Thanks for the great work.
However , when loading the car models files end with .pkl using pickle, some error occurs.
 
**ImportError: No module named objloader**
render_car_instances.py, line 68, in load_car_models, at position https://github.com/ApolloScapeAuto/dataset-api/blob/2a781056de76bdbf115bbf9fb185e6b12b9f9ea9/car_instance/render_car_instances.py#L60
when running self.car_models[model.name] = pkl.load(f)

**Comment by Pony-Kelei** [comment]
when using python2

**Comment by ZNorah** [comment]
Have you solved this problem?

**Comment by leiverandres** [comment]
Hi @Pony-Kelei I'm experiencing the same issue, did you figure out what the problem was?
