### ISSUE TITLE
Cannot download dataset from web page links

### ISSUE THREAD

**Issue by edumotya** [ApolloScapeAuto/dataset-api#24]
Maybe this is not the proper place for this issue. Anyway, I cannot use the dataset links of your [web page](http://apolloscape.auto/car_instance.html) for 3D Car Instance (or any other dataset).  

I think it is a CORS issue, since my JS console shows:

`Failed to load http://www.baidu.com/search/error.html?tc=3192971…: Response for preflight is invalid http://apolloscape.auto/car_instance.html (redirect)`

**Comment by DefineFC** [comment]
Same here

**Comment by sibozhang** [comment]
no issue now
