### ISSUE TITLE
Camera intrinsic for camera 6

### ISSUE THREAD

**Issue by stevenwudi** [ApolloScapeAuto/dataset-api#3]
Hi, (at least for car instance track) I found out that in `render_car_instances.py`
when try to acquire camera intrinsic, it's dependent upon the names of the cameras:
`intrinsic = self.dataset.get_intrinsic(image_name)`.  (That's for camera 5 and camera 6, there are two different intrinsic. )

However, after close examination, images from camera 6 (using camera 6 intrinsic) always exhibit misalignment (171206_065804067_Camera_6): 

![171206_065804067_camera_6](https://user-images.githubusercontent.com/4302669/44442264-a188a600-a603-11e8-8a08-66f4cf8c6eab.png)

And after enforcing all images using intrinsic from camera 5, we eliminate the misalignment. So I guess images from camera 6 should also use intrinsic from camera 5, isn't? Hence the code should be changed accordingly as well.
E.g.: `intrinsic = self.dataset.get_intrinsic("Camera_5")`
Mesh image from camera 6 using camera 5 intrinsic:

![171206_065804067_camera_6](https://user-images.githubusercontent.com/4302669/44442379-69359780-a604-11e8-9658-fa9e49ea0eba.png)

**Comment by jianghe01** [comment]
i think the images u shown are the same image toke by camera 5. u should project models on images toke by camera 6 with the different parameters. The camera 6 is another camera beside camera 5.

**Comment by stevenwudi** [comment]
@jianghe01  Images from Camera 5 or Camera 6 is decided by the image name right. As I have shown above 171206_065804067_Camera_6 (along with other 13 images in train, train split ending with * *_Camera_6), they all suffer from the same misalignment. But using camera 5 intrinsic will have correct alignment.
@jianghe01  Can you double check this? Thanks

**Comment by XibinSong** [comment]
@stevenwudi , Hi, there are only 14 images of the training data and 3 images of testing data are captured by camera 6. The intrinsic parameters of camera 5 and camera 6 are little different, we have updated the intrinsic parameters of camera 5 and camera 6 named "intrinsic_camera_5.txt" and "intrinsic_camera_6.txt"in the project website of github (https://github.com/ApolloScapeAuto/dataset-api/tree/master/car_instance). You can re-download the project if it is needed, thanks for the feedback.

**Comment by stevenwudi** [comment]
@XibinSong Thanks for the addition. I am afraid I didn't explain the situation well:

The camera intrinsic for 5 and 6 are given in the code `data.py` already.
And the original intrinsics are the same as the newly added `car_instance/intrinsic_Camera_6.txt` and `car_instance/intrinsic_Camera_6.txt`.

However, the issue is that instead of using camera 5 intrinsic for *Camera_5 and camera 6 intrinsic for *Camera_6, the 3d to 2D projection visualisation shows that using only camera 5 intrinsic for *Camera_6 (and *Camera_5) make more sense since it's better aligned. 

I would suggest running the visualisation for verification:
 `image_vis, mask, depth = visualizer.showAnn(setting.image_name)` and change the code from
` intrinsic = self.dataset.get_intrinsic(image_name)` to
 `intrinsic = self.dataset.get_intrinsic("Camera_5")`

**Comment by XibinSong** [comment]
@stevenwudi , Hi, I am sorry for the mis-understanding, we will repair it soon, thanks for the explanation.
