### ISSUE TITLE
What is the actual meaning of the 'name' field in laneMarkDetection.py

### ISSUE THREAD

**Issue by huangyuyao** [ApolloScapeAuto/dataset-api#31]
I want to know the actual meaning of such as 'ds_y_dn' etc. It is useful for analysis of data unbalance and merging with other datasets. Thanks very much!

**Comment by ApolloScapeAuto** [comment]
Thanks for you interest. 

ds_y_dn means: double solid, yellow, dividing no pass. 

By the way, you can find the detailed descriptions in the following link: 
https://github.com/ApolloScapeAuto/dataset-api/blob/master/lane_segmentation/LanemarkDiscription.pdf
