### ISSUE TITLE
车道线线上提交结果，一直报错

### ISSUE THREAD

**Issue by universea** [ApolloScapeAuto/dataset-api#34]
![image](https://user-images.githubusercontent.com/13444641/69779903-91874b00-11e4-11ea-9ade-162966d1cd38.png)

测试集是用的官网上的这个:http://apolloscape.auto/lane_segmentation.html 中的  Test_ColorImage_road05.tar.gz ，总共885张图片，并且是按照这个压缩包的目录结构做的提交结构：
├── test
│   ├── ColorImage_road05
│   │   ├── 171206_064731347_Camera_5.png
│   │   ├── ...

能否提供给我测试集的完整的csv文件目录呀，或者分数很低的一个提交样例，很着急，麻烦啦~

**Comment by universea** [comment]
谢谢 Dingfu，改成如下目录结构就好了。

├── test
│ ├── road05
│ │ ├── 171206_064731347_Camera_5.png
│ │ ├── ...

**Comment by hyalvin** [comment]
Ang, btw, how long does it cost to get the eval results for you?
