### ISSUE TITLE
关于lane_segmentation/helpers/laneMarkDetection.py的疑问

### ISSUE THREAD

**Issue by joehammer934** [ApolloScapeAuto/dataset-api#4]
在lane_segmentation/helpers/laneMarkDetection.py中，labels里面trainID分别为15和27的color是相同的，均为(128, 0, 0)，请问一下，在标注的时候，这两种车道线的颜色就是相同的吗？

**Comment by dingfuzhou** [comment]
Hi joehammer934,

Thank you very much for pointing out this mistake. During the labeling process,  each class has a unique label id and the color is just used for visualization purpose. By the way, we will update the laneMarkDetection.py file by giving another color code for "id 230".  At the same time, we will update the ground truth file accordingly.
