### ISSUE TITLE
Result server down?

### ISSUE THREAD

**Issue by stevenwudi** [ApolloScapeAuto/dataset-api#40]
Hi， I have tried to submit my result for Car 3D instance. But it seems that the server is not responding to give the result feedback. Can we still evaluate our result on the platform?

**Comment by cardwing** [comment]
Same question. I managed to submit the results for lane segmentation but failed. Maybe the server is down.

**Comment by Adyoshkin** [comment]
@cardwing @stevenwudi Have you managed to get results of evaluation? I've submitted results for lane segmentation.

**Comment by stevenwudi** [comment]
@cardwing @Adyoshkin 
Hi, Yes. I did manage to have the server working for my submission for Car Instance (I need to put my results into the test folder).

But more importantly, I email the website maintenance staffs to inform my submission--> They need to verify the server is running properly. I would suggest emailing them: apollo-scape@baidu.com 

I would like to thank the ApolloScape members, it's a very good opendata platform and it might be easy to maintain the website. Hope they will provide a good evaluation service here.

**Comment by cardwing** [comment]
@Adyoshkin The server seemed to work normally several days ago since I finally obtained the performance of the trained models (The trained ResNet-101 can achieve 46.63% mIoU and trained ERFNet can achieve 43.48% mIoU).

**Comment by sibozhang** [comment]
The evaulation server maybe down when running a long time. If the server down, pls send a email to apollo-scape@baidu.com. Thank you!
