### ISSUE TITLE
Where can I get the data structure of sample trajectory？

### ISSUE THREAD

**Issue by IvanXL** [ApolloScapeAuto/dataset-api#41]
Trajectory dataset:  
I want to render a trajectory in a 2d rgb image. I found there is no rgb image for predcition train/test data, while the sample data has trajectories and rgb images. But the data format of sample trajectory is different with prediction train. How can I parse sample trajectory, and render it with its rgb image?

**Comment by Juwankim** [comment]
Same Question...

**Comment by sibozhang** [comment]
Each line is the info for one traffic-agent in one frame. The info for each line is in order by the following: timestamp, id, width, length, type, position_x, position_y, velocity_x, velocity_y.

added to [q & a](https://github.com/ApolloScapeAuto/dataset-api/tree/master/trajectory_prediction)

**Comment by fgqile** [comment]
in the prediction_train folder, but there are so many files.  and in the prediction_test folder, there is only one file.  can you tell me how I deal with it?
![image](https://user-images.githubusercontent.com/64899378/128960539-27b35a3d-bdb0-4c20-83ef-451e9a850338.png)

![image](https://user-images.githubusercontent.com/64899378/128960566-1f270401-c82a-417a-8e05-20ec584b0b1b.png)
