### ISSUE TITLE
Lidar dataset Capture Freq

### ISSUE THREAD

**Issue by ChaturvediShilpa** [ApolloScapeAuto/dataset-api#44]
Hi, 

I want to know how to interpret the sampling frequency of lidar dataset. For example, it is mentioned that 3D Lidar Object Detection and Tracking dataset :
"The 3D Lidar object detection and tracking benchmark consists of about 53min training sequences and 50min testing sequences. The data is captured at 10 frames per second and labeled at 2 frames per second."

How does this translates to number of points per seconds ?

**Comment by sibozhang** [comment]
no correlation between number of points per seconds with capture frequency
