### ISSUE TITLE
Unable to Download Detection/Tracking Dataset

### ISSUE THREAD

**Issue by rsvarma** [ApolloScapeAuto/dataset-api#46]
I was interested in downloading the detection/tracking pcd zip files, but whenever I click on the download buttons on the website, nothing happens. I am able to download the datasets from all other sections but detection/tracking, and I have signed in with the user license. I was hoping for some help in downloading the detection/tracking dataset.

**Comment by sibozhang** [comment]
I am able to download pcd by logged in google account. I use chrome and download window should pop up when click.
