### ISSUE TITLE
The submitted data format of lane segmentation

### ISSUE THREAD

**Issue by sea5ismine** [ApolloScapeAuto/dataset-api#5]
I submitted the .zip file as this format:
test.zip
├── test
│   ├── road05
│   │   ├── image_name1.png
│   │   ├── image_name2.png
But I got a 'fail' feedback. I found that the description of data format between LanemarkDiscription.pdf and http://apolloscape.auto/lane_segmentation.html is different. Do I need to upload a .csv file within the .zip file? Could you show me the correct format of submitted data?
Besides, the ignore label of Camera6's image is incorrect. It should be located at the bottom left corner of image, but now at bottom right instead.
![171206_042435834_camera_6_bin](https://user-images.githubusercontent.com/9206296/44661158-5b38aa00-aa3c-11e8-80b1-c2fd9ab79384.png)

**Comment by sea5ismine** [comment]
Thanks for your help, but I still got a 'fail' feedback. I'm sure that prediction images have the same name and same size as testing images. I wonder whether "road05" is the correct "road_name", or there are some important points in README.md that I didn't notice. Many thanks!

**Comment by dingfuzhou** [comment]
Hi sea5ismine,

Sorry for missing your message. I will check again and try to find the reason.

**Comment by dingfuzhou** [comment]
Hi sea5ismine, 
The ground truth has been updated. An example is as below:
![image](https://user-images.githubusercontent.com/6109054/45342850-bbe5ec00-b5d1-11e8-81fa-40866a2c1281.png)

**Comment by sea5ismine** [comment]
Thanks for your help! That's very kind of you! :-)

**Comment by dingfuzhou** [comment]
> Thanks for your help! That's very kind of you! :-)

You are welcome, that's our job. Please let us know if you face any problems.  Cheers.
