### ISSUE TITLE
轨迹预测提交结果 failed

### ISSUE THREAD

**Issue by CuttlefishXuan** [ApolloScapeAuto/dataset-api#51]
你好，

我在轨迹预测模块提交结果时，一直显示failed；
并且，用dataset-api/trajectory_prediction/evaluation.py测试时（用的github提供的gt和res），报错如下：
File "evaluation.py", line 42, in evaluation
AttributeError: 'map' object has no attribute 'count'

请问你有遇到过这个问题吗？

**Comment by sibozhang** [comment]
Reboot the server. It should works now.
