### ISSUE TITLE
Number of 3D Tracks

### ISSUE THREAD

**Issue by mvpatel2000** [ApolloScapeAuto/dataset-api#56]
Hello, 

I am part of a team at Stanford releasing another dataset. We would like to include ApolloScape for comparison and are trying to figure out the number of 3D tracks for pedestrians in the benchmark. Could you kindly provide us those numbers? We were unable to find these ourselves and don't see a contact email -- on the website, it only says to post an issue here. We would love to include ApolloScape in our paper.

**Comment by sibozhang** [comment]
Hi, 
3d tracks object counts for cars, bicycles, and pedestrians are as follows:
248504, 70751, 82176
I will add these numbers to the website. 
If you have more questions about the dataset, please email sibozhang1@gmail.com.
Thank you!
Please cite @inproceedings{ma2019trafficpredict,
  title={Trafficpredict: Trajectory prediction for heterogeneous traffic-agents},
  author={Ma, Yuexin and Zhu, Xinge and Zhang, Sibo and Yang, Ruigang and Wang, Wenping and Manocha, Dinesh},
  booktitle={Proceedings of the AAAI Conference on Artificial Intelligence},
  volume={33},
  pages={6120--6127},
  year={2019}
}
