### ISSUE TITLE
Not able to download Lane_Segmentation dataset

### ISSUE THREAD

**Issue by kaishijeng** [ApolloScapeAuto/dataset-api#59]
Access https://ad-apolloscape.cdn.bcebos.com/ColorImage_road02.tar.gz and got the following error:

Hmmm… your Internet access is blockedFirewall or antivirus software may have blocked the connection.
Try:

Checking the connection
Checking firewall and antivirus configurations
Running Windows Network Diagnostics
ERR_NETWORK_ACCESS_DENIED

However, other datasets, like stereo is OK

Any idea why this happens.

Thanks,

**Comment by sibozhang** [comment]
I can download it without a problem. Please try login and download again.
