### ISSUE TITLE
About raw data

### ISSUE THREAD

**Issue by SlingHe** [ApolloScapeAuto/dataset-api#61]
Hi, Can you provide the raw datasets labelling 3d car instances? I want to know whether can provide the images and corresponding lidar scans? Just similar to KITTI which including both 'images' and 'velodynes'. Thanks a lot.

**Comment by sibozhang** [comment]
Please refer http://apolloscape.auto/inpainting.html for synchronized Labeled image and LiDAR scanned point clouds.

**Comment by scutzzy** [comment]
http://apolloscape.auto/inpainting.html only has sample data. Is it full data or full data will be released later?
