### ISSUE TITLE
轨迹预测结果不一致

### ISSUE THREAD

**Issue by guoyage** [ApolloScapeAuto/dataset-api#67]
首先非常感谢您提供这么精彩的研究内容，我有个问题需要请教一下，我使用相同的prediction_result.txt文件，但是网站的评估结果WSADE=1.3751与我自己运行evaluation.py代码后得到的WSADE=15.461365441512218 结果不同，请问一下这是什么原因造成的，非常希望能收到您回复。

**Comment by sibozhang** [comment]
Because our server compare result with full ground truth data.
