### ISSUE TITLE
I can't find dataset include GPS data, wheather Apolloscape include GPS data about car. 

### ISSUE THREAD

**Issue by Simplefree** [ApolloScapeAuto/dataset-api#70]
I want to find GPS data, which like KITTI，include latitude, longitude, altitude. 
But I just found pose data, which not include initial GPS data. 
I want to know wheather Apolloscape include GPS data about car??? 
Thanks a lot.

**Comment by sibozhang** [comment]
For 3d detection and tracking, we have pose information which including GPS location.
