### ISSUE TITLE
TrafficPredict baseline model  evaluation.py results are different

### ISSUE THREAD

**Issue by Bigtuo** [ApolloScapeAuto/dataset-api#87]
('WSADE:', 35.52371758873721)
('ADEv, ADEp, ADEb:', 35.73273751079803, 36.26945977251843, 33.367651902349614)
('WSFDE:', 18.967547482188102)
('FDEv, FDEp, FDEb:', 24.395048414119227, 16.602132518526005, 20.269549720996242)

**Comment by sibozhang** [comment]
baseline result is for demo。
