### ISSUE TITLE
dataset-api and self-localization

### ISSUE THREAD

**Issue by ShreyasSkandan** [ApolloScapeAuto/dataset-api#9]
Is the current version of the dataset-api supposed to work out of the box with the self-localization dataset?

I have some questions regarding the dataset. I'm trying to generate depth images from the point clouds.

1. The point clouds are provided in multiple parts. For example in Road11:
Point cloud folder contents: Part001...Part008
Image folder contents: Record001...Record037
How are these related? Do you provide code for handling the Part00x.pcd files?

2. I'm trying to use proj_point_cloud.py but it appears as if the file structure required by this script differs from the dataset provided as there is no train/test folder and it assumes a pc_sub.pcd file at the leaf of the point cloud folder structure.

3. Is there a way to generate depth images without using the renderer provided. It seems as though there are multiple driver related instabilities to getting GLEW to comfortably run on a machine and moving back nvidia driver versions isn't an option since I'm using a team machine.

Thanks in advance, and I look forward to working with this dataset. It looks like your team has put tremendous effort into putting this dataset together and making it available to the public. Your work is much appreciated.

Best regards,
S

**Comment by pengwangucla** [comment]
> Is the current version of the dataset-api supposed to work out of the box with the self-localization dataset?

Yes, it should work. 
> I have some questions regarding the dataset. I'm trying to generate depth images from the point clouds.
> 
> 1. The point clouds are provided in multiple parts. For example in Road11:
>    Point cloud folder contents: Part001...Part008
>    Image folder contents: Record001...Record037
>    How are these related? Do you provide code for handling the Part00x.pcd files?

Since each point cloud of a scene is very large, so we divided to several parts. You may project all the parts to the same image and find the minimum depth at each pixel to obtain a depth map. 
 
> 2. I'm trying to use proj_point_cloud.py but it appears as if the file structure required by this script differs from the dataset provided as there is no train/test folder and it assumes a pc_sub.pcd file at the leaf of the point cloud folder structure.
It should be compatible with the pcd file we provided on webpage. http://apolloscape.auto/self_localization.html

> 3. Is there a way to generate depth images without using the renderer provided. It seems as though there are multiple driver related instabilities to getting GLEW to comfortably run on a machine and moving back nvidia driver versions isn't an option since I'm using a team machine.

I am not sure about it, haven't test other version, since we use shader for enlarging the point to make the rendered depth densely cover the image.

> 
> Thanks in advance, and I look forward to working with this dataset. It looks like your team has put tremendous effort into putting this dataset together and making it available to the public. Your work is much appreciated.
> 
> Best regards,
> S

**Comment by ShreyasSkandan** [comment]
Alright thanks, I will try to do what you mentioned.

**Comment by msinto93** [comment]
Hi, I have some further questions on this...

> Since each point cloud of a scene is very large, so we divided to several parts. You may project all the parts to the same image and find the minimum depth at each pixel to obtain a depth map. 

How can I associate the provided poses with points in the point cloud. I have X,Y,Z pose coordinates, how do these relate to coordinates of the point cloud given that the point cloud is split into multiple parts. I am not concerned with projecting onto an image, I just want to know these poses with respect to the full point cloud.

> It should be compatible with the pcd file we provided on webpage. http://apolloscape.auto/self_localization.html

You say that it should be compatible with the files you provide. However the code is looking for a 'pc_sub.pcd' file as the original poster said, I don't see this file in the dataset, only 'PartX.pcd' files?

Finally, I assume the point clouds here are just range data. Will you be releasing the semantically-labelled point cloud at any point?

Thanks for all your work and for any help you can give on this.

**Comment by zyzwhdx** [comment]
Hi,
I cannot find the pcd file download link on the official website http://apolloscape.auto/self_localization.html.
Could you please tell me where you downloaded the backgroud 3D point clouds?
Thanks a lot!
