### ISSUE TITLE
ApolloScape Semantic Segmentation

### ISSUE THREAD

**Issue by LAZOO61** [ApolloScapeAuto/dataset-api#99]
Hey,

I need the ApolloScape dataset to train my neural network. But I can't download the dataset because the website is not accessible. I need semantically segmented images.

**Comment by sibozhang** [comment]
sorry for the inconvenience, it will be back soon.

**Comment by sibozhang** [comment]
Each dataset can be download directly from github links. For semantically segmented images, download https://ad-apolloscape.cdn.bcebos.com/road01_ins.tar.gz,  https://ad-apolloscape.cdn.bcebos.com/road02_seg.tar.gz

**Comment by sibozhang** [comment]
website is online now
